# Generated by Django 4.0.3 on 2022-03-09 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_image_product_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
    ]
